ALTER TABLE USERS
ADD COLUMN INSS VARCHAR(100),
ADD COLUMN FIRST_NAME VARCHAR(100),
ADD COLUMN STREET VARCHAR(100),
ADD COLUMN NUMBER VARCHAR(100),
ADD COLUMN POSTAL_CODE VARCHAR(100),
ADD COLUMN CITY VARCHAR(100)

